name: Generate Pac-Man Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *" # Her gün gece 00:00'da çalışır
  workflow_dispatch: # Manuel olarak da tetiklenebilir

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Pac-Man contribution graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: safeapric0t
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push generated files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "update pacman contribution graph" || echo "No changes to commit"
          git push
